BirthdayBot/BirthdayBot.Api/Areas/Edit/Controllers/PersonController.cs
using System.Web.Mvc;

namespace BirthdayBot.Api.Areas.Edit.Controllers
{
    public class PersonController : Controller
    {
        // GET: Edit/Person
        public ActionResult Index()
        {
            return View();
        }

        // GET: Edit/Person/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Edit/Person/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Edit/Person/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Edit/Person/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Edit/Person/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Edit/Person/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Edit/Person/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BirthdayBot/BirthdayBot.Api/Controllers/BirthdayWebController.cs
using System;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BirthdayBot.Core.Models;
using BirthdayBot.Core.Repositories;
// ReSharper disable InconsistentNaming

namespace BirthdayBot.Api.Controllers
{
    public class BirthdayWebController : Controller
    {
        // GET: Birthday
        public ActionResult Index(string Message, bool? Success)
        {
            if (Message != null && Success != null)
            {
                ViewBag.Message = Message;
                ViewBag.Success = Success.Value;
            }

            var connectionString = ConfigurationManager.ConnectionStrings["BirthdayTableCstr"].ConnectionString;
            var partition = ConfigurationManager.AppSettings["PartitionKey"];

            var databaseController = new DatabaseController(connectionString, partition);
            
            var people =
                databaseController.GetAllPersonEntities()
                    .OrderBy(i => (i.Active ? "A" : "B"))
                    .ThenBy(i => i.Name)
                    .ToArray();
            return View(people);
        }

        // GET: Birthday/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Birthday/Create
        [HttpPost]
        public ActionResult Create(PersonEntity person, string save, string cancel, FormCollection collection)
        {
            try
            {
                var connectionString = ConfigurationManager.ConnectionStrings["BirthdayTableCstr"].ConnectionString;
                var partition = ConfigurationManager.AppSettings["PartitionKey"];

                if (string.IsNullOrEmpty(save))
                {
                    return RedirectToAction("Index", new { Message = "Avbrutt opprettelse", Success = false });
                }

                if (person.Name == null || person.Birthday == null)
                {
                    throw new HttpException(400, "Bad request. Name and birthday must be set");
                }

                person.Active = true;
                person.RowKey = Guid.NewGuid().ToString();
                person.LastCongratulation = DateTime.Now.AddYears(-10);
                person.PartitionKey = partition;
                person.Name = person.Name.Trim();
                person.SlackUserName = person.SlackUserName.Trim();                

                var databaseController = new DatabaseController(connectionString, partition);
                databaseController.InsertOrReplacePersonEntity(person);

                return RedirectToAction("Index", new {Message = $"Opprettet {person.Name}", Success = true});
            }
            catch (HttpException)
            {
                throw;
            }
            catch (Exception e)
            {
                throw new HttpException(500, "Error occured: " + e.Message);
            }
        }

        // GET: Birthday/Edit/5
        public ActionResult Edit(string RowKey)
        {
            var connectionString = ConfigurationManager.ConnectionStrings["BirthdayTableCstr"].ConnectionString;
            var partition = ConfigurationManager.AppSettings["PartitionKey"];

            var databaseController = new DatabaseController(connectionString, partition);
            var people = databaseController.GetAllPersonEntities().Where(p => p.RowKey == RowKey).ToArray();

            if (!people.Any())
            {
                throw new HttpException(404, "There was no person with row key " + RowKey);
            }

            return View(people.First());
        }

        // POST: Birthday/Edit/5
        [HttpPost]
        public ActionResult Edit(string RowKey, string Name, string save, string cancel, DateTime? Birthday, string Gender, string SlackUserName, bool? Active, FormCollection collection)
        {
            try
            {
                if (string.IsNullOrEmpty(save) || RowKey == null)
                {
                    return RedirectToAction("Index");
                }

                if (Name == null || Birthday == null)
                {
                    throw new HttpException(400, "Bad request. Name and birthday must be set");
                }

                var connectionString = ConfigurationManager.ConnectionStrings["BirthdayTableCstr"].ConnectionString;
                var partition = ConfigurationManager.AppSettings["PartitionKey"];

                var databaseController = new DatabaseController(connectionString, partition);
                var people = databaseController.GetAllPersonEntities().Where(p => p.RowKey == RowKey).ToArray();
                var person = people.Single();

                if (!string.IsNullOrEmpty(Name))
                {
                    person.Name = Name.Trim();
                }

                person.Birthday = Birthday;

                if (!string.IsNullOrEmpty(Gender))
                {
                    person.Gender = Gender;
                }

                if (!string.IsNullOrEmpty(SlackUserName))
                {
                    person.SlackUserName = SlackUserName.Trim();
                }

                if (Active != null)
                {
                    person.Active = Active.Value;
                }

                databaseController.InsertOrReplacePersonEntity(person);                    

                return RedirectToAction("Index", new { Message = $"Oppdaterte {person.Name}", Success = true });
            }
            catch (HttpException)
            {
                throw;
            }
            catch (Exception e)
            {
                throw new HttpException(500, "Error occured: " + e.Message);
            }
        }
    }
}

BirthdayBot/BirthdayBot.Api/Views/BirthdayWeb/Create.cshtml
@using BirthdayBot.Core.Models
@model PersonEntity

@{
    ViewBag.Title = "CREATE";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Opprett ny</h2>

@using (Html.BeginForm("Create", "BirthdayWeb", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Birthday)
        @Html.TextBoxFor(model => model.Birthday, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SlackUserName)
        @Html.TextBoxFor(model => model.SlackUserName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gender)
        @Html.TextBoxFor(model => model.Gender, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Active)
        @Html.CheckBoxFor(model => model.Active, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <input type="submit" name="save" value="Save" />
        <input type="submit" name="cancel" value="Cancel" />
    </div>
}

BirthdayBot/BirthdayBot.Api/Views/BirthdayWeb/Edit.cshtml
@using BirthdayBot.Core.Models
@model PersonEntity

@{    
    ViewBag.Title = ("Edit: " + Model.Name);
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit: @Model.Name</h2>

@using (Html.BeginForm("Edit", "BirthdayWeb", FormMethod.Post))
{

    <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, new {@class = "form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Birthday)
        @Html.TextBoxFor(model => model.Birthday, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SlackUserName)
        @Html.TextBoxFor(model => model.SlackUserName, new {@class = "form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gender)
        @Html.TextBoxFor(model => model.Gender, new {@class = "form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Active)
        @Html.CheckBoxFor(model => model.Active, new {@class = "form-control"})
    </div>

    @Html.HiddenFor(model => model.RowKey)    

    <br />
    <input type="submit" name="save" value="Save" />
    <input type="submit" name="cancel" value="Cancel" />
}

BirthdayBot/BirthdayBot.Api/Views/BirthdayWeb/Index.cshtml
@model IEnumerable<BirthdayBot.Core.Models.PersonEntity>

@{
    ViewBag.Title = "Birthday List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.Success != null && (ViewBag.Success as bool?) != null)
{
    var b = ViewBag.Success as bool?;
    if (b != null && b.Value)
    {
        <div class="alert alert-success fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>@ViewBag.Message</strong>
        </div>
    }
    else if (b != null)
    {
        <div class="alert alert-danger fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>@ViewBag.Message</strong>
        </div>
    }
}

<h2>Birthday List</h2>

@Html.ActionLink("Legg til ny...", "Create", "BirthdayWeb", null, null)

<div class="container-fluid">
    <table class="table table-striped">
        <tr>
            <th>Name</th>
            <th>SlackUser</th>
            <th>Birthday</th>
            <th>Active</th>
            <th>Last Congratulated</th>            
        </tr>

        @foreach (var person in Model)
        {
            <tr class="person">
                <td>
                    @Html.ActionLink(person.Name, "Edit", "BirthdayWeb", new { person.RowKey }, null)
                </td>
                <td>@person.SlackUserName</td>
                <td>@person.Birthday</td>
                
                @if (person.Active)
                {
                    <td class="person-active">@person.Active</td>
                }
                else
                {
                    <td class="person-inactive">@person.Active</td>
                }

                <td>@person.LastCongratulation</td>                
            </tr>
        }

    </table>
</div>